name: wl-pprint-annotated
version: 0.1.0.0
description: Wadler/Leijen pretty printer with support for annotations and modernized API. Annotations are useful for coloring. See wl-pprint-console.
synopsis: Pretty printer with annotation support
category: Text
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2011-2012 Edward A. Kmett, 2000 Daan Leijen
license: BSD3
github: minad/wl-pprint-annotated

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1,
  GHC == 8.2.1,
  GHC == 8.4.3,
  GHC == 8.6.1

default-extensions:
- FlexibleInstances
- TypeSynonymInstances
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- DefaultSignatures

ghc-options:
- -Wall
#- -Widentities
#- -Wmonomorphism-restriction
#- -Wincomplete-uni-patterns
#- -Wincomplete-record-updates
#- -Wtabs
#- -fprint-potential-instances

dependencies:
- base       >= 4.8  && < 5
- containers >= 0.4  && < 0.7
- text       >= 0.11 && < 1.3
- deepseq    >= 1.4  && < 1.6

when:
  - condition: impl(ghc < 8.0)
    dependencies: semigroups >= 0.9 && < 1

library:
  source-dirs: src

tests:
  wl-pprint:
    main: WLPPrintTests.hs
    source-dirs: test
    dependencies:
      - wl-pprint-annotated
      - tasty
      - tasty-hunit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
